name: lint
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip" # caching pip dependencies
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: python3 -m pip install tox
      - name: Run linter
        run: tox -e lint
