name: test
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python3 tests/service_desk.py
