name: deploy
on:
  push:
    branches:
      - "*" # Include all branches
      - "!master" # Exclude the master branch
      - "!main" # Exclude the master branch
  pull_request:
    branches:
      - "*" # Include all branches
      # - "!master" # Exclude the master branch
      # - "!main" # Exclude the master branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup nodejs
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "yarn"
      - run: yarn install
      - name: Run tests
        run: yarn test --run
      - name: Test building the pages
        run: yarn run build
